### ISSUE TITLE
Change distribution strategy

### ISSUE THREAD

**Issue by lwansbrough** [Wildhoney/Standalone#7]
Hey Adam, great work on this project - it's really awesome. I have a problem with the current package though. I'm developing my React components so they work both in regular React applications and Custom Elements alike. The trouble is that I am already using Webpack for my stuff - the existence of multiple copies of React (in my Webpack package and yours) is causing a conflict which React is complaining about.

I think there are a couple ways to solve this. The first would be to define React as an external dependency in the Webpack config. This isn't optimal though. A solution I see a lot is to have a secondary process that just runs babel on your src and outputs the result. This way, the source files can be used efficiently without the need for Webpack.

Alternatively I can just tell my Webpack to transpile the standalone module but I'm not sure that's a good way to do it.

**Comment by Wildhoney** [comment]
@lwansbrough thanks!

I love the idea of specifying React as an external dependency! It seems as though it would solve the huge issue of having multiple instances of React. How would we go about implementing that?

**Comment by Wildhoney** [comment]
Specified React as a dependency, along with others. Filesize is now ~14kb.
